sudo: required

services:
  - docker

language: cpp

env:
  global:
    - COMPOSE_VERSION: 1.22.0
    - secure: c2jXdHRsHBUvKZQ1U7rWLyJWQsyrO1awXI9MhnTdSHW4IzoyoFFdohGgGZ3/DDePrQ1R63NAShHxW35wPuxMS7Qk89x0xraCAI3XEDo6P4r9FGRXXaF1njCWuDbSZY4UM8ON6AYlrrMd2vOeLXMiDwMIkU8jCg6o10Z4l3wi8YjAe5zTKBfP7Re/oj4ORlnLJ0h2C7FWQHeOpfb57ppeq+g7G4UkKW7jTxUT/W3BtDXQE/jtlt77FejEhLhk5ls04VccY+RkBZtCBf1QzC2n59leiJ8k5krPXus+qvmnXrnuxZWskdMtw7Cx3oGxL+nqQTkDDptXZGjDPL3HwViefWBm+A+Y0b7sUMqFQVKCxWGc3s373DqYUm2tkykKMu3TMSS39toODyeKQiKoGMJXKNdZ04N3K/Seg3QugcCKM0QDdLGxnhmXck2Ft1+5p+kD0e5L2m61/teINKUb8zOvVzrNbH19Bw2gkN0GzT64CM60hfk1GX11AATc68S+p+LIOM9m1c/OvgEu1eI5FuRHfeEG6o7nZsxtNgCwFWnErqasT4ZvSN5CH14yNCJR+g28qBNdPnCfK5apswzTOZx4iKpkVm1hQg/aknYYBk7RhM0C3hdAXHUJU9Hp7O2s6I9fYcantd4OwsB9lSmiUt6bU5dHZM0cYWWl5L7S1samAfA=
    - secure: ICZ4SXhZvHh7YyDwjTd5JPvrnxjjDC++uTxJF6Qk5ws77NUF8jtfZ/AAKuuo/VcrTvNP2saExBBKJZG7zP0tJvmMDvDQ9Ci3sIpE1Bth3L9i3NzgfiNZoZZFiloYYwnbMIzH09uwQp4Yp+e+Wb9ocGCBD9k2OTESZkEBq24MBW7lLH0PmlcQLbjg/13Kj0TVhGwfByZPf3DkNhTnG8KnJZ94bz9hasSVnVdC4GOPWk3OCfKck4y09rVAXRnD4QxBfpdEnsDgfNSeb0WGpITkiIDNY7kLYL0pW70o/KoyI9AkgsOjjr4lWnzk+j2v/IhS3XXtd4hPJOlOHXSY/uGBtyX68GIXgyLZoAN0wvgwtv48pvNewEM+dKXtkKSV7kuchJr/eO+fy5vqXvvIpU9zWc2t/p22fLx5OL8OXnMpe/uvwu0G5B2XVC8ROSkE+KUi07kSXRSDzj3m8fp6ZgamsicoLqU29ug5EhSMtHZTHqNYz4vs0Opc66I36iZ/uRvpahEZcs7qtiL6VcsiOyoJM955R5pwDdo8viqInu1wfIGYgfU/CfB0HB26QRa+/hHZRpbnBCxH6PoX17yPNkhO0pWk/8cY+huxlvwqWb8DGkuI3XQNbfG0C00vLxJ651ykZrBV0HvilSAr8rbMYTeL4Ct3ra5nFnABCgr1lmVJy/Q=

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose -v

script:
  - docker-compose build travis

notifications:
  slack:
    secure: RUiplbRX8scnvplFZhBIvSJxPDs/qCcBiMmSZnocILQsHrZMCIhv0eNoAT6FWIkXpJbS4l56BFbSdZH25/qNl/cdNwbn/YCc4N4fketeYduLcWNpwOfbf41vjFIXEbzo6wboFjlIPJDZgQFbtMThoJ2Gx6J2nBLB719j4Skj5C58yx6/ScioXZZ1LIXEE1aeOwRnju+OqX/o0dvUNrnP+6XnMtuYSicml10JV5tj3r9IJQuSAD6Bv0l/2eMparJ5UboRMwtCy5GVLfetky6WARmESJP+bKhvYE1+FR3AdRmzA47rmE+c7fZzyybSRKeUlhWPUVatTLbWxpB4ivXxKfRWqe1RiYUIAQz8U2EhWgiuR47/1qYvQ4Lefq2pgZzbCTy4Z8rL4+CjuQqRrweAIS2AQuyWfcnv01BuJX7mmdR+jA0FYWSBxdTgrJLJ70y6ZiV6QGWYFW4x9mot3E6O+vh1LfI56ctpJfwHgIFwc0xN8rMhhkTNzEG911QAZPLsNp1+v18vXF5StHXc4sTM62IagVEifTjoVkJCTytKtqBIn+ZrAcxIBBZk8Mre9doT3ulCjRtzmGLEmGGHN429jY0ufjw1pdAml/a6FDKlKwp7/QZ49qeg23/OkkZCJ1MQ3kducjtO0qCV2DcCS7dS2b8q7ZJGH+gcWGc82XAsFgs=
